services:
  app:
    build: .
    container_name: pltsci-sdet-assignment
    command: python app/main.py
    ports:
      - 8080:8080
    volumes:
      - .:/robotic-hoover-service
  tests:
    build: .
    command: behave
    depends_on:
      - app